Changes in the file
anuket-project/RA2 pull request #28
Opened 2024-09-11 13:34 UTC by Aryan-Singla

2024-09-12 06:42 UTC, CsatariGergely requested changes

2024-09-12 06:42 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/.github/workflows/review-docs.yml
This file should go to the `.github/workflows` folder from the **root** of the repo.

2024-09-12 06:42 UTC, CsatariGergely commented on .vale/.vale-config/2-Hugo.ini
This file is not needed.

2024-09-12 07:47 UTC, Aryan-Singla commented on doc/ref_arch/kubernetes/.github/workflows/review-docs.yml
Updated

2024-09-12 07:47 UTC, Aryan-Singla commented on .vale/.vale-config/2-Hugo.ini
Removed

2024-09-13 08:26 UTC, CsatariGergely requested changes

2024-09-13 08:26 UTC, CsatariGergely commented on .github/workflows/review-docs.yml
> +    paths:
```suggestion
```

2024-09-13 08:26 UTC, CsatariGergely commented on .github/workflows/review-docs.yml
> +      - "ospo-book/content/en/*.md"
```suggestion
```

2024-09-13 08:26 UTC, CsatariGergely commented on .github/workflows/review-docs.yml
> +          vale --output=".vale.tmpl" --no-exit ospo-book/content/en
```suggestion
          vale --output=".vale.tmpl" --no-exit .
```

2024-09-19 13:48 UTC, CsatariGergely approved these changes

2024-09-22 12:31 UTC, CsatariGergely approved these changes

2024-09-22 12:33 UTC, CsatariGergely commented
I think this is as good as this can get. 
We still need to find a way to figure out how to make `github-pr-check` work. We are working on the same issue in Nephio also (https://github.com/nephio-project/docs/pull/172)

2024-09-30 09:27 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter01.rst
> +     - Virtual Extendable LAN
```suggestion
     - Virtual eXtensible LAN
```
https://en.wikipedia.org/wiki/Virtual_Extensible_LAN

2024-09-30 09:28 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter04.rst
> +       hence it is easily integrated into higher-level and is not comparable tooling for the full lifecycle management of
```suggestion
       hence it is easily integrated into higher-level tooling for the full lifecycle management of
```

2024-10-07 09:09 UTC, rgstori approved these changes

2024-10-07 09:09 UTC, merged