[ra2] proofread ch5 and ch7
anuket-project/RA2 pull request #38
Opened 2024-11-11 12:21 UTC by rgstori

2024-11-17 08:23 UTC, CsatariGergely requested changes

2024-11-17 08:23 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter05.rst
> +   - Use namespaces to establish security boundaries between tenants.
```suggestion
   - Use Namespaces to establish security boundaries between tenants.
```

Namespaces here are referring to the Kubernetes object

2024-11-17 08:45 UTC, CsatariGergely requested changes

2024-11-17 08:45 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter05.rst
> +   - Create and define cluster network policies.
```suggestion
   - Create and define cluster Network Policies.
```

2024-11-17 08:45 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter05.rst
> +   - Isolate sensitive workloads using namespaces.
```suggestion
   - Isolate sensitive workloads using Namespaces.
```

2024-11-17 08:45 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter05.rst
> +OpenVAS, or other open-source or commercial tools) to identify and mitigate threats and vulnerabilities.
```suggestion
OpenVAS, or other open source or commercial tools) to identify and mitigate threats and vulnerabilities.
```

2024-11-17 08:45 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +Functional gaps exist between available open-source
```suggestion
Functional gaps exist between available open source
```

2024-11-17 08:45 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +production-grade open-source solution.
```suggestion
production-grade open source solution.
```

2024-11-18 10:09 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter05.rst
> +Implement a robust patch management process to address security vulnerabilities, ensure compliance, maintain uptime,
```suggestion
A robust patch management process should be implemented to address security vulnerabilities, ensure compliance,
```

2024-11-18 10:09 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter05.rst
> +and enable feature enhancements.
```suggestion
maintain uptime, and enable feature enhancements.
```

2024-11-18 10:10 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter05.rst
> +- Deploy security products providing allowlisting, behavior monitoring, and anomaly detection to prevent malicious
@CsatariGergely can you please allowlist allowlisting?

2024-11-18 10:13 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +address the gap.
```suggestion
..
   **Gap description:** Describe missing functionality from
    the related requirements in known implementations. Include
    references to ongoing work in the target project that may
    address the gap.
```

2024-11-18 10:14 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +"none".
```suggestion
   **Baseline project:**  Identify the upstream project
   (e.g., *Kubernetes*) where the gap exists. If none, state
   "none".
```

2024-11-18 10:15 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +pages resources`.
```suggestion
:ref:`chapters/chapter03:management of memory and huge pages resources`.
```

2024-11-18 10:18 UTC, petorre approved these changes

2024-11-18 10:28 UTC, merged