[RA2 Ch2 Ch4] AF_XDP specs
anuket-project/RA2 pull request #5
Opened 2024-02-06 22:31 UTC by petorre

Closes [#3354](https://github.com/anuket-project/anuket-specifications/issues/3354)

If needed, the long list of prerequisites is [here](https://github.com/intel/afxdp-plugins-for-kubernetes?tab=readme-ov-file#prerequisites).

2024-02-07 07:39 UTC, CsatariGergely approved these changes

2024-02-07 12:33 UTC, rgstori requested changes

2024-02-07 12:33 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter04.rst
> +     - AF_XDP Zero Copy capable netdev’s
```suggestion
     - AF_XDP Zero Copy capable netdevs
```

2024-02-07 12:33 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter04.rst
> +     - AF_XDP Zero Copy capable netdev’s (dependent on AF_XDP Zero Copy NIC driver) must be available in Kubernetes
```suggestion
     - AF_XDP Zero Copy capable netdevs (dependent on AF_XDP Zero Copy NIC driver) must be available in a compliant Kubernetes cluster
```

2024-02-07 12:33 UTC, rgstori commented
thanks @petorre , added just a couple of tweaks

2024-02-11 22:56 UTC, petorre commented
> thanks @petorre , added just a couple of tweaks

Thanks. I committed the change, but changed "cluster" to "worker" as it is per worker node.

2024-02-12 10:09 UTC, rgstori approved these changes

2024-02-12 10:09 UTC, merged