[RA2] add cert-manager
anuket-project/RA2 pull request #7
Opened 2024-03-05 17:28 UTC by rgstori

fixes https://github.com/anuket-project/anuket-specifications/issues/3299

2024-03-11 10:06 UTC, petorre approved these changes

2024-03-11 12:41 UTC, CsatariGergely requested changes

2024-03-11 12:41 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter03.rst
> +- Renewal of the certificate before expiry is handled by cert-manager and is transparent to the CNF. Steps 2 and 3
Maybe we should use ordered list if there are references to the sequence numbers.

2024-03-11 12:41 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter03.rst
> +  the diagram belong to the same K8s namespace.
What diagram?

2024-03-28 14:19 UTC, rgstori commented
thanks @CsatariGergely - should be all fixed now

2024-03-28 14:27 UTC, CsatariGergely approved these changes

2024-04-08 09:04 UTC, merged